name = "hok-codex-worker"
main = "src/index.ts"
compatibility_date = "2026-01-01"
account_id = "5bca87c509482eb499947f96a5e38d0a"

[triggers]
crons = ["0 */12 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "hok-codex-db"
database_id = "a9c68163-013f-43e7-bcf8-87efd6b4ce6e"

[vars]
ENVIRONMENT = "production"
AI_API_URL = "https://api.groq.com/openai/v1/chat/completions"
